### ISSUE TITLE
App Crash in android - Huawei - Android 7

### ISSUE THREAD

**Issue by SamiYousef** [odemolliens/react-native-sim-cards-manager#51]
Exception in HostObject::get for prop 'SimCardsManager': java.lang.NoClassDefFoundError: android.telephony.euicc.EuiccManager

**Comment by odemolliens** [comment]
**EuiccManager** added in [API level 28](https://developer.android.com/guide/topics/manifest/uses-sdk-element#ApiLevels)

**Comment by SamiYousef** [comment]
Should I upgrade minSdkVersion to 28, do you think you could recommend other solutions to fix the crash?

**Comment by beqramo** [comment]
HI  @odemolliens ,
I have same issue, what should I do if user's device API is less than 28?

**Comment by Neeal20** [comment]
Did you manage to find something working ? Application is crashing on every device Android 8 and less even with condition isEsimSupported to false

**Comment by Neeal20** [comment]
Solution is  : 

```javascript
let SimCardsManagerModule
  if ((Platform.OS === 'android' && Platform.Version >= 28)) {
     SimCardsManagerModule = require('react-native-sim-cards-manager').default
  }
```
