### ISSUE TITLE
index file is missing - V1.0.11

### ISSUE THREAD

**Issue by SamiYousef** [odemolliens/react-native-sim-cards-manager#52]
import SimCardsManagerModule from 'react-native-sim-cards-manager';

Unable to resolve path to module 'react-native-sim-cards-manager'

**Comment by MatteoBuffo** [comment]
Same here. @SamiYousef if you don't mind missing [those features from the latest release](https://github.com/odemolliens/react-native-sim-cards-manager/releases/tag/1.0.11), you could install the previous version of this library while this gets fixed.

**Comment by odemolliens** [comment]
https://github.com/odemolliens/react-native-sim-cards-manager/releases/tag/1.0.16

Can you retest with that version, please?

**Comment by MatteoBuffo** [comment]
@odemolliens now I get this error:
```
Error: While trying to resolve module `react-native-sim-cards-manager` from file `[file with include SimCardsManagerModule]`, the package `[Myapp]\node_modules\react-native-sim-cards-manager\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`[Myapp]\node_modules\react-native-sim-cards-manager\index.ts`. Indeed, none of these files exist:

  * [Myapp]\node_modules\react-native-sim-cards-manager\index.ts(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.
jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * [Myapp]\node_modules\react-native-sim-cards-manager\index.ts\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.an
droid.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
```

After manually changing `index.js` to `index.ts` it worked, so I guess you should do another release that fixes this.

**Comment by odemolliens** [comment]
😅
https://github.com/odemolliens/react-native-sim-cards-manager/releases/tag/1.0.17
