### ISSUE TITLE
android 7 - API Level 24 - App Not Load

### ISSUE THREAD

**Issue by SamiYousef** [odemolliens/react-native-sim-cards-manager#53]
ERROR  Error: Exception in HostObject::get(propName:SimCardsManager): java.lang.NoClassDefFoundError: android.telephony.euicc.EuiccManager
 
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
        
 ERROR  Invariant Violation: Failed to call into JavaScript module method AppRegistry.runApplication(). Module has not been registered as callable. Registered callable JavaScript modules (n = 10): Systrace, JSTimers, HeapCapture, SamplingProfiler, RCTLog, RCTDeviceEventEmitter, RCTNativeAppEventEmitter, GlobalPerformanceLogger, JSDevSupportModule, HMRClient.
        A frequent cause of the error is that the application entry file path is incorrect. This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.

**Comment by AlehBarushka** [comment]
same problem on Android 8.0 (API Level 26)

**Comment by odemolliens** [comment]
Can you retry with .16 release? 

The .11 release was bugged

**Comment by MargusSalk** [comment]
We also ran into same issue some months ago with Android SDK < 28. Tried couple of different things and I think what fixed it in my [fork](https://github.com/MargusSalk/react-native-sim-cards-manager) was not importing `euicc` package directly in SimCardsManagerModule and putting all the methods that use its functionality behind version checks. Not so familiar with Android development, so can't say that this actually was 100% issue. But that appeared to do it.

**Comment by AlehBarushka** [comment]
@odemolliens 
I updated the version and got this error:

`Error: Exception in HostObject::get for prop 'SimCardsManager': java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/euicc/EuiccManager;, js engine: hermes`

**Comment by odemolliens** [comment]
https://github.com/odemolliens/react-native-sim-cards-manager/releases/tag/1.0.18
