### ISSUE TITLE
Duplicated 'address' params for setup ESIM

### ISSUE THREAD

**Issue by faezmurshidi** [odemolliens/react-native-sim-cards-manager#54]
Hi,

First of all, thank you for creating and maintaining this repo.

Question regarding the params for setup Esim, from documentation below it seems there's a duplicated key for 'address'.

Entry parameters | Mandatory | Description
-- | -- | --
address | N/A | The address of the carrier network’s eSIM server
confirmationCode | N/A | The provisioning request’s confirmation code, provided by the network operator when initiating an eSIM download
iccid | N/A | The provisioning request’s eUICC identifier
address | N/A | The provisioning request’s Integrated Circuit Card Identifier
matchingId | N/A | The provisioning request’s matching identifier
oid | N/A | The provisioning request’s Object Identifier

<br class="Apple-interchange-newline">

Also, based on the description. The params should be updated to:

Entry parameters | Mandatory | Description
-- | -- | --
address | N/A | The address of the carrier network’s eSIM server
confirmationCode | N/A | The provisioning request’s confirmation code, provided by the network operator when initiating an eSIM download
euid/eid | N/A | The provisioning request’s eUICC identifier
iccid | N/A | The provisioning request’s Integrated Circuit Card Identifier
matchingId | N/A | The provisioning request’s matching identifier
oid | N/A | The provisioning request’s Object Identifier

<br class="Apple-interchange-newline">

**Comment by odemolliens** [comment]
https://github.com/odemolliens/react-native-sim-cards-manager/pull/55

Thank you!
