### ISSUE TITLE
Android Permission Required

### ISSUE THREAD

**Issue by shubham-imoney** [odemolliens/react-native-sim-cards-manager#60]
The documentation states that _READ_PHONE_STATE_ permission is required in Android, but on Android 13 I get the following error even though _READ_PHONE_STATE_ permission is given 
`[Error: Something goes wrong to fetch simcards: getPhoneNumberFromFirstAvailableSource: Neither user 10423 nor current process has android.permission.READ_PHONE_NUMBERS or android.permission.READ_PRIVILEGED_PHONE_STATE or carrier privileges]`
Providing _READ_PHONE_NUMBERS_ permission works on Android 13 and Android 10 device. Is it safe to assume that _READ_PHONE_NUMBERS_ is sufficient and READ_PHONE_STATE is not required for Android 8+ ?

**Comment by eliezerBrasilian** [comment]
I have the same issue, running on android device

**Comment by cloudex1** [comment]
same issue on Android 13, any solution?

**Comment by xiiao5777** [comment]
same issue on Android 13, any solution?

**Comment by xiiao5777** [comment]
i think i found the solution, in the index.ts file, find a function that call requestCellularNetworkPermission it have a const granted = await PermissionsAndroid.request coding in side if(Platform.Version == android), edit that code become
`let granted = ''
    if(Platform.Version >= 33){ 
      granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_PHONE_NUMBERS, 
        rationale ?? { 
          title: 'App Permission', 
          message: 'App needs access to get informations of your cellular network', 
          buttonNeutral: 'Ask Me Later', 
          buttonNegative: 'Cancel', 
          buttonPositive: 'OK', 
        }); 
      granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE, 
        rationale ?? { 
          title: 'App Permission', 
          message: 'App needs access to get informations of your cellular network', 
          buttonNeutral: 'Ask Me Later', 
          buttonNegative: 'Cancel', 
          buttonPositive: 'OK', 
        }); 
    }else{ 
        granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE, 
          rationale ?? { 
            title: 'App Permission', 
            message: 'App needs access to get informations of your cellular network', 
            buttonNeutral: 'Ask Me Later', 
            buttonNegative: 'Cancel', 
            buttonPositive: 'OK', 
          }); 
    }`

**Comment by odemolliens** [comment]
Thanks for the feedback
