### ISSUE TITLE
Error: #2003 (badRequest): Request is unsuccessful. https://api.adapty.io/api/v1/sdk/purchase/play-store/token/v2/validate/ Code: 400, Response: {"errors":[{"detail":"Google service account key is not set in Adapty dashboard.","status":"400","source":{"pointer":"/data"},"code":"GOOGLE_SERVICE_ACCOUNT_KEY_IS_NOT_SET_ERROR"}]}

### ISSUE THREAD

**Issue by eliezerBrasilian** [odemolliens/react-native-sim-cards-manager#63]
the error occurs in tests, i think its related to the bug on seting package name and json key on adapty account

https://github.com/odemolliens/react-native-sim-cards-manager/assets/93846923/7425f890-c0e1-4ef3-ac15-09e9ade30b4f

**Comment by odemolliens** [comment]
What is the link with the [react-native-sim-cards-manager](https://github.com/odemolliens/react-native-sim-cards-manager) library?
