### ISSUE TITLE
The setupEsim function doesn't distinguish success from cancellation

### ISSUE THREAD

**Issue by Uriah-Eisenstein-ATT** [odemolliens/react-native-sim-cards-manager#65]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-sim-cards-manager@1.0.18` for the project I'm working on.

The setupEsim function doesn't distinguish a success result from cancellation, at least on iOS (I think also on Android, but I'm not an Android developer so I'm not sure the flow is the same). Since the function returns a boolean in case of no error, I've patched it to return true only on success, and return false if the user cancels.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-sim-cards-manager/ios/SimCardsManager.m b/node_modules/react-native-sim-cards-manager/ios/SimCardsManager.m
index ffcb291..4f9b794 100644
--- a/node_modules/react-native-sim-cards-manager/ios/SimCardsManager.m
+++ b/node_modules/react-native-sim-cards-manager/ios/SimCardsManager.m
@@ -90,8 +90,8 @@ @implementation SimCardsManager
                     NSError *error = [NSError errorWithDomain:@"react.native.simcardsmanager.handler" code:1 userInfo:nil];
                     reject(@"3", @"CTCellularPlanProvisioningAddPlanResultUnknown - Can't setup eSim due to unknown error", error);
                 }else{
-                    //CTCellularPlanProvisioningAddPlanResultSuccess
-                    resolve(@(true));
+                    //CTCellularPlanProvisioningAddPlanResultSuccess or CTCellularPlanProvisioningAddPlanResultCancel
+                    resolve(@(result == CTCellularPlanProvisioningAddPlanResultSuccess));
                 }
                 [[UIApplication sharedApplication] endBackgroundTask:backgroundTaskIdentifier];
             }];
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Regards,
Uriah Eisenstein

**Comment by odemolliens** [comment]
Added to develop branch, thanks!
