### ISSUE TITLE
Something goes wrong to fetch simcards: getPhoneNumberFromFirstAvailableSource: Neither user 10705 nor current process has android.permission.READ_PHONE_NUMBERS or android.permission.READ_PRIVILEGED_PHONE_STATE or carrier privileges

### ISSUE THREAD

**Issue by hareesh7777** [odemolliens/react-native-sim-cards-manager#66]
i'm gettig this error while doing both getSimCards and getSimCardsNative in android
please help on this

Something goes wrong to fetch simcards: getPhoneNumberFromFirstAvailableSource: Neither user 10705 nor current process has android.permission.READ_PHONE_NUMBERS or android.permission.READ_PRIVILEGED_PHONE_STATE or carrier privileges

**Comment by odemolliens** [comment]
Linked to #60
