### ISSUE TITLE
Debugging SimCardsManagerModule.setupEsim method on Android

### ISSUE THREAD

**Issue by raffiot** [odemolliens/react-native-sim-cards-manager#76]
Hello 👋
I'm currently trying to integrate setupEsim method in my code as
```typescript
try {
  if (Platform.OS === 'ios') {
    await Linking.openURL(appleEsimSetupUrl);
  } else if (Platform.OS === 'android') {
    const result = await SimCardsManagerModule.setupEsim({
      confirmationCode,
      address: smdpAddress,
    });
    if (!result) throw new Error('Error while setting up eSIM');
  } else {
    throw new Error('Unsupported Platform');
  }
} catch (error) {
  Sentry.captureException(error);
}
```

This call to `setupEsim` never resolves and I'm trying to debug it.
We did the setup steps:
1. Our eSIM provider specified on his side: package name and SHA1 of our app on the eSIM profiles
2. Our app is correctly signed with "App signing key certificate"

Looking at android logs we get the following
```
EuiccController         com.android.phone                    I  Caller can't manage subscription on target SIM or  User consent is required for resolving port index. Ask user's consent first
```
And the resultCode from response intent is `EMBEDDED_SUBSCRIPTION_RESULT_RESOLVABLE_ERROR`
I tried both the `downloadSubscription` method with `switchAfterDownload` to `true` and `false`

The configuration is the following:
- expo managed
- "react-native-sim-cards-manager": "^1.0.21",
- contain this patch the patch mentioned [here](https://github.com/odemolliens/react-native-sim-cards-manager/pull/74/files)
- We have requested the needed permissions
```typescript
// app.config.ts
export default {
  expo: {
    android: {
      permissions: [
        'android.permission.READ_PHONE_STATE',
      ],
    }
  }
}
```

Is there any way that I can check what went wrong in the downloadSubscription? What is the metadata profile on the eSIM? And what is specified in our profile's access rule file (ARF)?
Thanks for your help!

**Comment by odemolliens** [comment]
Hello 👋 !

I'm quite busy currently but you can maybe have a look at this:

https://android.googlesource.com/platform/frameworks/opt/telephony/+/master/src/java/com/android/internal/telephony/euicc/EuiccController.java#606
![Screenshot 2024-06-05 at 13 21 18](https://github.com/odemolliens/react-native-sim-cards-manager/assets/2726958/3019d444-428d-4871-a6e2-e3e5c584e24b)

It really seems like you didn't ask for user consent properly

**Comment by raffiot** [comment]
Hey @odemolliens ,
Thanks for your quick answer, however we already requested the permission
Because following the documentation we added 
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" xmlns:tools="http://schemas.android.com/tools">
  ...
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
</manifest>
```
Using the `app.config.ts` as mentioned previously

And the authorisation is live on the app
![Screenshot_20240605-144030](https://github.com/odemolliens/react-native-sim-cards-manager/assets/17401598/d69ace3a-ad3f-4562-b58b-9243f679ee01)

Is there any other permission that we should ask for ?
Thanks

**Comment by odemolliens** [comment]
What about his: https://github.com/odemolliens/react-native-sim-cards-manager/blob/develop/index.ts#L34

**Comment by raffiot** [comment]
I added the request, the permission is requested and allowed, but still The setupEsim does not resolve... 
```typescript
try {
if (Platform.OS === 'ios') {
  await Linking.openURL(appleEsimSetupUrl);
} else if (Platform.OS === 'android') {
  const granted = await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.READ_PHONE_STATE,
    {
      title: 'App Permission',
      message:
        'App needs access to get informations of your cellular network',
      buttonNeutral: 'Ask Me Later',
      buttonNegative: 'Cancel',
      buttonPositive: 'OK',
    },
  );
  if (granted === PermissionsAndroid.RESULTS.GRANTED) {
    const result = await SimCardsManagerModule.setupEsim({
      confirmationCode: matchingId,
      address: smdpAddress,
    });
    if (!result) throw new Error('Error while setting up eSIM');
  } else {
    console.log('Phone permission denied');
  }
} else {
  throw new Error('Unsupported Platform');
}
} catch (error) {
console.log(error);
Sentry.captureException(error);
}
```
Do you have other ideas that I can try out ?

**Comment by again-this-coder** [comment]
Hi, facing same issue. I grant the access for the need permissions and get the following error, even though the device itself supports esim. Was able to add a esim manually 
[Error: EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription]

**Comment by raffiot** [comment]
Hi @again-this-coder,
What do you mean by "add a eSIM manually" ? You added added it yourself through code or by installation in your settings ? When did you get the error  `[Error: EMBEDDED_SUBSCRIPTION_RESULT_ERROR - Can't add an Esim subscription]` ?

**Comment by odemolliens** [comment]
@again-this-coder your error is not the same here. Please use https://github.com/odemolliens/react-native-sim-cards-manager?tab=readme-ov-file#android to see what's going wrong @again-this-coder 

It's difficult to provide support in this case as there are no similar issues reported in production on my side. Can you please verify that everything is properly configured with SDMP+?

**Comment by raffiot** [comment]
Thanks for your help guys, I finally found the solution:
1. In `SimCardsManagerModule.setupEsim` only `confirmationCode` argument is used (address can be left blank `''`) and `confirmationCode` need to be in the format `LPA:1$...`
2. The fix in [PR 74](https://github.com/odemolliens/react-native-sim-cards-manager/pull/74) was not working, because if  the PendingIntent was created with flag `PendingIntent.FLAG_IMMUTABLE` hence we couldn't retrieve error sent by EUICC Controller. I'll submit a PR in order to fix that problem.

**Comment by raffiot** [comment]
You can find the fix here:
https://github.com/odemolliens/react-native-sim-cards-manager/pull/77

**Comment by again-this-coder** [comment]
@raffiot hey, can I contact you somehow, I would like to discuss with you some esim functionality, I am not able to solve my issue and I was wondering if you are using esim the same way as me in my project

**Comment by raffiot** [comment]
Hey @again-this-coder, please send me an email at raphael@kolet.com, will be happy to help :)
