### ISSUE TITLE
issues with Android 14 and targetSdkVersion 34

### ISSUE THREAD

**Issue by kenneth-rangel-1global** [odemolliens/react-native-sim-cards-manager#80]
in some phone with samsung OS 6.1 June patch profile fails to install.
Also if i set targetSdkVersion 34 the installation prompt doesn't appear.

Anyone is having similar issues?

**Comment by MohammadKurjieh** [comment]
@kenneth-rangel-1global, I was facing the same issue. This should be resolved by this PR: #77
