### ISSUE TITLE
isEsimSupported initiate Euicc Manager before a check for Android version and cause a crash.

### ISSUE THREAD

**Issue by i3bdul3ziz** [odemolliens/react-native-sim-cards-manager#82]
ERROR Error: Exception in HostObject::get(propName:SimCardsManager): java.lang.NoClassDefFoundError: android.telephony.euicc.EuiccManager

Impact happened every where you import the module on the top of any file.

this is still happening on `isEsimSupported` for Android below 9 and reproducable, i suggest to apply the same condition applied before on `setupEsim` before initMgr to fix the same issue.

as it will fix it.

**Comment by odemolliens** [comment]
included in 1.0.24
